// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AdminLayout = "_AdminLayout";
                public readonly string _AuthenticatedHeader = "_AuthenticatedHeader";
                public readonly string _FocusedLayout = "_FocusedLayout";
                public readonly string _FocusedLayoutLarge = "_FocusedLayoutLarge";
                public readonly string _FocusedWizardLayout = "_FocusedWizardLayout";
                public readonly string _Footer = "_Footer";
                public readonly string _InteractiveCatalogAssetsLayout = "_InteractiveCatalogAssetsLayout";
                public readonly string _Layout = "_Layout";
                public readonly string _LogOnLayout = "_LogOnLayout";
                public readonly string _QuoteBuilderLayout = "_QuoteBuilderLayout";
                public readonly string _UnauthenticatedHeader = "_UnauthenticatedHeader";
                public readonly string Error = "Error";
                public readonly string PageNotFound = "PageNotFound";
            }
            public readonly string _AdminLayout = "~/Views/Shared/_AdminLayout.cshtml";
            public readonly string _AuthenticatedHeader = "~/Views/Shared/_AuthenticatedHeader.cshtml";
            public readonly string _FocusedLayout = "~/Views/Shared/_FocusedLayout.cshtml";
            public readonly string _FocusedLayoutLarge = "~/Views/Shared/_FocusedLayoutLarge.cshtml";
            public readonly string _FocusedWizardLayout = "~/Views/Shared/_FocusedWizardLayout.cshtml";
            public readonly string _Footer = "~/Views/Shared/_Footer.cshtml";
            public readonly string _InteractiveCatalogAssetsLayout = "~/Views/Shared/_InteractiveCatalogAssetsLayout.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _LogOnLayout = "~/Views/Shared/_LogOnLayout.cshtml";
            public readonly string _QuoteBuilderLayout = "~/Views/Shared/_QuoteBuilderLayout.cshtml";
            public readonly string _UnauthenticatedHeader = "~/Views/Shared/_UnauthenticatedHeader.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string PageNotFound = "~/Views/Shared/PageNotFound.cshtml";
            static readonly _PartialsClass s_Partials = new _PartialsClass();
            public _PartialsClass Partials { get { return s_Partials; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _PartialsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                }
                static readonly _AssetClass s_Asset = new _AssetClass();
                public _AssetClass Asset { get { return s_Asset; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _AssetClass
                {
                    static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                    public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                    public class _ViewNamesClass
                    {
                        public readonly string AssetComments = "AssetComments";
                        public readonly string AssetDetails = "AssetDetails";
                        public readonly string AssetNavigator = "AssetNavigator";
                        public readonly string ListItem = "ListItem";
                        public readonly string NewComment = "NewComment";
                    }
                    public readonly string AssetComments = "~/Views/Shared/Partials/Asset/AssetComments.cshtml";
                    public readonly string AssetDetails = "~/Views/Shared/Partials/Asset/AssetDetails.cshtml";
                    public readonly string AssetNavigator = "~/Views/Shared/Partials/Asset/AssetNavigator.cshtml";
                    public readonly string ListItem = "~/Views/Shared/Partials/Asset/ListItem.cshtml";
                    public readonly string NewComment = "~/Views/Shared/Partials/Asset/NewComment.cshtml";
                }
                static readonly _CatalogClass s_Catalog = new _CatalogClass();
                public _CatalogClass Catalog { get { return s_Catalog; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _CatalogClass
                {
                    static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                    public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                    public class _ViewNamesClass
                    {
                        public readonly string AssetRow = "AssetRow";
                        public readonly string ImportResultFailureRow = "ImportResultFailureRow";
                        public readonly string ImportResultSkippedRow = "ImportResultSkippedRow";
                        public readonly string ImportResultSuccessRow = "ImportResultSuccessRow";
                    }
                    public readonly string AssetRow = "~/Views/Shared/Partials/Catalog/AssetRow.cshtml";
                    public readonly string ImportResultFailureRow = "~/Views/Shared/Partials/Catalog/ImportResultFailureRow.cshtml";
                    public readonly string ImportResultSkippedRow = "~/Views/Shared/Partials/Catalog/ImportResultSkippedRow.cshtml";
                    public readonly string ImportResultSuccessRow = "~/Views/Shared/Partials/Catalog/ImportResultSuccessRow.cshtml";
                }
                static readonly _ContactClass s_Contact = new _ContactClass();
                public _ContactClass Contact { get { return s_Contact; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _ContactClass
                {
                    static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                    public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                    public class _ViewNamesClass
                    {
                        public readonly string ListItem = "ListItem";
                    }
                    public readonly string ListItem = "~/Views/Shared/Partials/Contact/ListItem.cshtml";
                }
                static readonly _DashboardClass s_Dashboard = new _DashboardClass();
                public _DashboardClass Dashboard { get { return s_Dashboard; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _DashboardClass
                {
                    static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                    public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                    public class _ViewNamesClass
                    {
                        public readonly string GettingStarted = "GettingStarted";
                    }
                    public readonly string GettingStarted = "~/Views/Shared/Partials/Dashboard/GettingStarted.cshtml";
                }
                static readonly _HeaderClass s_Header = new _HeaderClass();
                public _HeaderClass Header { get { return s_Header; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _HeaderClass
                {
                    static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                    public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                    public class _ViewNamesClass
                    {
                        public readonly string Help = "Help";
                    }
                    public readonly string Help = "~/Views/Shared/Partials/Header/Help.cshtml";
                }
                static readonly _QuoteClass s_Quote = new _QuoteClass();
                public _QuoteClass Quote { get { return s_Quote; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _QuoteClass
                {
                    static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                    public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                    public class _ViewNamesClass
                    {
                        public readonly string ListItem = "ListItem";
                    }
                    public readonly string ListItem = "~/Views/Shared/Partials/Quote/ListItem.cshtml";
                    static readonly _NewClass s_New = new _NewClass();
                    public _NewClass New { get { return s_New; } }
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public partial class _NewClass
                    {
                        static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                        public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                        public class _ViewNamesClass
                        {
                            public readonly string Step1 = "Step1";
                            public readonly string Step2 = "Step2";
                        }
                        public readonly string Step1 = "~/Views/Shared/Partials/Quote/New/Step1.cshtml";
                        public readonly string Step2 = "~/Views/Shared/Partials/Quote/New/Step2.cshtml";
                    }
                }
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
